// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ioygfrowctuklqlaului.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlveWdmcm93Y3R1a2xxbGF1bHVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNjg0OTMsImV4cCI6MjA1OTg0NDQ5M30.h6j64ZjbCKvt8uZTw4O-Ieiq2pzuv5yxENuHYV9RObE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);